import { describe, expect, it } from 'vitest';

import { createProtocolRegistry } from '@/protocol-core/registry';
import { registerBuiltInProtocols } from './index';

/** `registeredProtocolIds()` ALFABETİK döner; liste o sırayla yazılır. */
const BUILT_IN_IDS = [
  'ads-b',
  'ais',
  'arinc-429',
  'arp',
  'art-net',
  'as-interface',
  'ascii-protocol',
  'at-commands',
  'bacnet-ip',
  'bacnet-mstp',
  'ble-advertisement',
  'ble-gatt',
  'can-2-0a',
  'can-2-0b',
  'can-fd',
  'can-xl',
  'canopen',
  'cc-link',
  'cc-link-ie',
  'ccp',
  'cip',
  'cmos-uart',
  'coap',
  'cobs',
  'crsf',
  'custom-binary-protocol',
  'cyphal',
  'dali',
  'delimiter-based-protocol',
  'devicenet',
  'dhcp',
  'dmx512',
  'dnp3',
  'dns',
  'doip',
  'dronecan',
  'ethercat',
  'ethernet-ii',
  'ethernet-interface',
  'ethernet-ip',
  'flexray',
  'foundation-fieldbus',
  'ftp',
  'gnss-modem',
  'gnss-ubx',
  'hart',
  'hayes-command-set',
  'hdlc',
  'hdlc-based-marine',
  'http',
  'i2c',
  'i3c',
  'ibus',
  'icmp',
  'icmpv6',
  'iec-60870-5-101',
  'iec-60870-5-104',
  'iec-61850',
  'ieee-802-3',
  'io-link',
  'ipv4',
  'ipv6',
  'iso-14230',
  'iso-9141',
  'iso-tp',
  'j1939',
  'kiss',
  'knx',
  'length-based-protocol',
  'lin',
  'lldp',
  'lorawan',
  'lte-modem-at',
  'm-bus',
  'matter',
  'mavlink',
  'mdns',
  'microwire',
  'mil-std-1553',
  'modbus-ascii',
  'modbus-rtu',
  'modbus-tcp',
  'mode-s',
  'mqtt',
  'mqtt-sn',
  'nb-iot',
  'nmea-0183',
  'nmea-2000',
  'ntp',
  'obd-ii',
  'octal-spi',
  'one-wire',
  'opc-ua',
  'pmbus',
  'powerlink',
  'ppm',
  'ppp',
  'profibus-dp',
  'profinet',
  'psi5',
  'ptp',
  'pwm-servo',
  'quad-spi',
  'rs-232',
  'rs-422',
  'rs-485',
  'rtcm',
  'rtcp',
  'rtp',
  'sacn',
  'sae-j1850-pwm',
  'sae-j1850-vpw',
  'sbus',
  'sdlc',
  'sent',
  'sercos-iii',
  'slip',
  'smbus',
  'snmp',
  'some-ip',
  'spc',
  'spi',
  'syslog',
  'tcp',
  'telnet',
  'tftp',
  'ttl-uart',
  'uart',
  'uavcan-compatibility',
  'udp',
  'uds',
  'usb',
  'vlan-802-1q',
  'websocket',
  'wireless-m-bus',
  'xcp-on-can',
  'xcp-on-ethernet',
  'xmodem',
  'ymodem',
  'zigbee',
  'zmodem',
];

const EXPECTED_CATEGORY: Record<string, string> = {
  'ads-b': 'aerospace-uav',
  'arinc-429': 'aerospace-uav',
  'mil-std-1553': 'aerospace-uav',
  'mode-s': 'aerospace-uav',
  ais: 'marine-navigation',
  arp: 'network-ethernet',
  'art-net': 'building-automation',
  'as-interface': 'industrial-automation',
  'ascii-protocol': 'interfaces-framing',
  'at-commands': 'interfaces-framing',
  'bacnet-ip': 'building-automation',
  'bacnet-mstp': 'building-automation',
  'ble-advertisement': 'wireless-iot',
  'ble-gatt': 'wireless-iot',
  'can-2-0a': 'automotive',
  'can-2-0b': 'automotive',
  'can-fd': 'automotive',
  'can-xl': 'automotive',
  canopen: 'industrial-automation',
  'cc-link': 'industrial-automation',
  'cc-link-ie': 'industrial-automation',
  ccp: 'automotive',
  cip: 'industrial-automation',
  'cmos-uart': 'interfaces-framing',
  coap: 'network-ethernet',
  cobs: 'interfaces-framing',
  crsf: 'aerospace-uav',
  'custom-binary-protocol': 'interfaces-framing',
  cyphal: 'aerospace-uav',
  dali: 'building-automation',
  'delimiter-based-protocol': 'interfaces-framing',
  devicenet: 'industrial-automation',
  dhcp: 'network-ethernet',
  dmx512: 'building-automation',
  dnp3: 'industrial-automation',
  dns: 'network-ethernet',
  doip: 'automotive',
  dronecan: 'aerospace-uav',
  ethercat: 'industrial-automation',
  'ethernet-interface': 'interfaces-framing',
  'ethernet-ii': 'network-ethernet',
  'ethernet-ip': 'industrial-automation',
  flexray: 'automotive',
  'foundation-fieldbus': 'industrial-automation',
  ftp: 'network-ethernet',
  'gnss-modem': 'wireless-iot',
  'gnss-ubx': 'marine-navigation',
  hart: 'industrial-automation',
  'hayes-command-set': 'interfaces-framing',
  hdlc: 'interfaces-framing',
  'hdlc-based-marine': 'marine-navigation',
  http: 'network-ethernet',
  i2c: 'interfaces-framing',
  icmp: 'network-ethernet',
  icmpv6: 'network-ethernet',
  'iec-60870-5-101': 'industrial-automation',
  'iec-60870-5-104': 'industrial-automation',
  'iec-61850': 'industrial-automation',
  'ieee-802-3': 'network-ethernet',
  'io-link': 'industrial-automation',
  ipv4: 'network-ethernet',
  ipv6: 'network-ethernet',
  'iso-14230': 'automotive',
  'iso-9141': 'automotive',
  'iso-tp': 'automotive',
  j1939: 'automotive',
  kiss: 'interfaces-framing',
  knx: 'building-automation',
  'length-based-protocol': 'interfaces-framing',
  lldp: 'network-ethernet',
  lin: 'automotive',
  lorawan: 'wireless-iot',
  'lte-modem-at': 'wireless-iot',
  'm-bus': 'industrial-automation',
  mdns: 'network-ethernet',
  matter: 'wireless-iot',
  mavlink: 'aerospace-uav',
  'modbus-ascii': 'industrial-automation',
  'modbus-rtu': 'industrial-automation',
  'modbus-tcp': 'industrial-automation',
  mqtt: 'network-ethernet',
  'mqtt-sn': 'network-ethernet',
  'nb-iot': 'wireless-iot',
  'nmea-0183': 'marine-navigation',
  'nmea-2000': 'marine-navigation',
  ntp: 'network-ethernet',
  'obd-ii': 'automotive',
  'octal-spi': 'interfaces-framing',
  'one-wire': 'interfaces-framing',
  'opc-ua': 'industrial-automation',
  pmbus: 'interfaces-framing',
  powerlink: 'industrial-automation',
  ppm: 'aerospace-uav',
  ppp: 'interfaces-framing',
  'profibus-dp': 'industrial-automation',
  profinet: 'industrial-automation',
  psi5: 'automotive',
  ptp: 'network-ethernet',
  'pwm-servo': 'aerospace-uav',
  'quad-spi': 'interfaces-framing',
  'rs-232': 'interfaces-framing',
  'rs-422': 'interfaces-framing',
  'rs-485': 'interfaces-framing',
  rtcm: 'marine-navigation',
  rtcp: 'network-ethernet',
  rtp: 'network-ethernet',
  sacn: 'building-automation',
  'sae-j1850-pwm': 'automotive',
  'sae-j1850-vpw': 'automotive',
  sdlc: 'interfaces-framing',
  sent: 'automotive',
  'sercos-iii': 'industrial-automation',
  slip: 'interfaces-framing',
  smbus: 'interfaces-framing',
  i3c: 'interfaces-framing',
  microwire: 'interfaces-framing',
  ibus: 'aerospace-uav',
  sbus: 'aerospace-uav',
  snmp: 'network-ethernet',
  'some-ip': 'automotive',
  spc: 'automotive',
  spi: 'interfaces-framing',
  syslog: 'network-ethernet',
  tcp: 'network-ethernet',
  telnet: 'network-ethernet',
  tftp: 'network-ethernet',
  'ttl-uart': 'interfaces-framing',
  uart: 'interfaces-framing',
  'uavcan-compatibility': 'aerospace-uav',
  udp: 'network-ethernet',
  uds: 'automotive',
  usb: 'interfaces-framing',
  'vlan-802-1q': 'network-ethernet',
  websocket: 'network-ethernet',
  'wireless-m-bus': 'industrial-automation',
  'xcp-on-can': 'automotive',
  'xcp-on-ethernet': 'automotive',
  xmodem: 'interfaces-framing',
  ymodem: 'interfaces-framing',
  zigbee: 'wireless-iot',
  zmodem: 'interfaces-framing',
};

describe('registerBuiltInProtocols', () => {
  it('registers every built-in engine', () => {
    const registry = createProtocolRegistry();
    registerBuiltInProtocols(registry);

    expect(registry.registeredProtocolIds()).toEqual(BUILT_IN_IDS);
  });

  it('stays quiet on a second call — StrictMode runs startup effects twice', () => {
    const registry = createProtocolRegistry();
    registerBuiltInProtocols(registry);

    expect(() => registerBuiltInProtocols(registry)).not.toThrow();
    expect(registry.registeredProtocolIds()).toEqual(BUILT_IN_IDS);
  });

  it('does not load any module while registering', () => {
    const registry = createProtocolRegistry();
    registerBuiltInProtocols(registry);

    // Lazy sözleşmesi: kayıt ucuz, yükleme talep üzerine. Loader kayıt anında
    // koşsaydı açılışta üç parser da indirilirdi.
    for (const id of BUILT_IN_IDS) {
      expect(registry.getLoadedPlugin(id), id).toBeUndefined();
    }
  });

  it('loads the real plugin behind each id', async () => {
    const registry = createProtocolRegistry();
    registerBuiltInProtocols(registry);

    for (const id of BUILT_IN_IDS) {
      const plugin = await registry.loadProtocolPlugin(id);
      // Registry yüklenen modülün id'sini kayıt anahtarıyla karşılaştırır; buraya
      // gelmek kayıt ile modülün eşleştiğinin de kanıtıdır.
      expect(plugin.id, id).toBe(id);
      expect(plugin.category, id).toBe(EXPECTED_CATEGORY[id]);
      expect(plugin.exampleFrames.length, `${id} has no example frames`).toBeGreaterThan(0);
      expect(registry.getLoadedPlugin(id), id).toBe(plugin);
    }
    // Varsayılan 5000ms, kayıt büyüdükçe (her dalga +birkaç dynamic import)
    // tam paket koşusunda worker rekabeti altında marjinal hâle geliyordu —
    // izolasyonda <500ms, tam pakette gözlemlenen bir kez 5000ms'yi aştı.
  }, 15000);
});
