import type { CatalogDomain } from '../types';

/**
 * Domain 1 — 5 aile, 40 protokol (8 + 9 + 3 + 3 + 17).
 *
 * Bu domain'in ayırt edici yanı: buradaki kayıtların çoğu bir *taşıyıcı*, üst
 * seviye bir protokol değil. Kaynak iki yanılgıyı özellikle vurguluyor ve
 * katalog metinleri bunları bozmamalı:
 *   - UART ≠ RS-232 (biri framing, öteki elektriksel katman)
 *   - RS-485 ≠ Modbus (doğru zincir: Modbus RTU → UART → RS-485 transceiver → A/B)
 *
 * `tabs` seçimi kural tabanlıdır, kanaat değil:
 *   - 'live' yalnız tarayıcıdan (Web Serial/WebUSB) ya da köprüden yakalanabilenlerde.
 *     Bit-senkron çerçeveleme (HDLC, SDLC) bunun dışındadır — özel yakalama donanımı
 *     ister, ilk sürüm log/import ile çalışır. Aynı nedenle akım-döngüsü arayüzleri
 *     (Current Loop, 4–20 mA) ve saf PHY sayfaları da 'live' taşımaz.
 *   - 'definitions' YALNIZ makine-okunur tanım dosyası olanlarda. Bu domain'de bu,
 *     kullanıcının kendi şemasını yazdığı dört custom framing protokolü ve
 *     cihaz-başına komut haritası içe aktarılabilen PMBus'tır. UART sayfasında
 *     'definitions' görünmemesi, sekme kuralının canlı kanıtıdır.
 */
export const interfacesFramingDomain: CatalogDomain = {
  id: 'interfaces-framing',
  name: 'Interfaces & Framing',
  summary:
    'Physical and low-level communication interfaces together with the general-purpose frame and stream protocols that turn a raw byte stream into decoded packets.',
  highlights: ['UART', 'RS-485', 'SPI', 'I²C', 'USB', 'HDLC'],
  families: [
    {
      id: 'serial-interfaces',
      name: 'Serial Interfaces',
      summary:
        'Asynchronous serial framing and the voltage, differential and current-loop layers that carry it between devices.',
      protocols: [
        {
          id: 'uart',
          name: 'UART',
          summary:
            'Asynchronous parallel-to-serial framing with no shared clock, used between MCUs, GNSS receivers, radio modems and debug consoles that agree on a baud rate in advance.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'timing', 'diagnostics', 'examples'],
          tools: [
            'Configuration',
            'Frame Visualizer',
            'Live UART Monitor',
            'UART Decoder',
            'UART Packet Builder',
            'Timing Calculator',
            'Baud Error Calculator',
            'Oversampling Analyzer',
            'Error Analyzer',
          ],
        },
        {
          id: 'ttl-uart',
          name: 'TTL UART',
          summary:
            'UART framing carried over TTL-compatible logic levels, where the real question is whether two boards can drive each other without a level translator.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'diagnostics', 'examples'],
          // Kaynağın ısrarı: 3.3V/5V seçtirip "uyumlu" demek yanlış — karar
          // datasheet'teki VIH/VIL/VOH/VOL değerleriyle verilir.
          tools: [
            'Logic-Level Configuration',
            'Logic Compatibility Check',
            'UART Frame View',
            'Live Monitor',
            'Level Compatibility Calculator',
            'Error/Warning View',
          ],
        },
        {
          id: 'cmos-uart',
          name: 'CMOS UART',
          summary:
            'UART framing at CMOS supply levels between SoCs and peripherals, where each direction has to be evaluated separately because output and input characteristics are rarely symmetric.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'diagnostics', 'examples'],
          tools: [
            'Supply Voltage',
            'Logic Thresholds',
            'TX→RX Compatibility',
            'RX→TX Compatibility',
            'Level Translation Check',
            'UART Frame View',
            'Live Monitor',
          ],
        },
        {
          id: 'rs-232',
          name: 'RS-232',
          summary:
            'Single-ended bipolar voltage layer between PCs, PLCs and instruments, where the UART bit stream is inverted onto mark/space levels and DTE/DCE wiring decides whether a null modem is needed.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'UART↔RS-232 Layer View',
            'Signal View',
            'DTE/DCE Analyzer',
            'Null-Modem Helper',
            'DB9 Pinout Helper',
            'Frame Decoder',
            'Live Monitor',
            'Timing Calculator',
            'Error Analyzer',
          ],
        },
        {
          id: 'rs-422',
          name: 'RS-422',
          summary:
            'Balanced differential point-to-multipoint link with one driver and up to ten receivers, used for encoders, navigation sensors and long-distance telemetry.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'timing', 'diagnostics', 'examples'],
          tools: [
            'Differential Signal View',
            'TX+/TX- View',
            'RX+/RX- View',
            'Full-Duplex Analyzer',
            'Voltage Difference Calculator',
            'Termination Helper',
            'Live Decoder',
            'Timing Calculator',
            'Diagnostics',
          ],
        },
        {
          id: 'rs-485',
          name: 'RS-485',
          summary:
            'Balanced differential multipoint bus used by most industrial field networks, where driver enable turnaround, termination, biasing and unit load budget decide whether the bus works at all.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'Physical Layer View',
            'Half-Duplex Analyzer',
            'Full-Duplex Analyzer',
            'A/B Differential View',
            'DE/RE Timing',
            'Driver Turnaround Analyzer',
            'Termination Calculator',
            'Bias/Fail-Safe Calculator',
            'Unit Load / Node Calculator',
            'Cable Delay Calculator',
            'Bus Timing',
            'Live Monitor',
            'Collision/Turnaround Analyzer',
            'Diagnostics',
          ],
          // Taksonomi 1.5 "Related Protocols": RS-485 sayfası kendi başına bir
          // protokol değil, bu dört protokolün altındaki taşıyıcı — kullanıcı
          // buradan üst katmana geçebilmeli.
          related: [
            'industrial-automation/modbus/modbus-rtu',
            'industrial-automation/modbus/modbus-ascii',
            'building-automation/bacnet/bacnet-mstp',
            'industrial-automation/classic-fieldbus/profibus-dp',
          ],
        },
        {
          id: 'current-loop',
          name: 'Current Loop',
          summary:
            'Interface class that carries information as loop current rather than line voltage, so long cable resistance does not corrupt the value as long as compliance voltage holds.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'data', 'diagnostics', 'examples'],
          tools: [
            'Digital Current Loop View',
            'Loop Voltage',
            'Loop Current',
            'Cable Resistance',
            'Receiver Burden',
            "Ohm's Law Calculator",
            'Diagnostics',
          ],
        },
        {
          id: '4-20-ma',
          name: '4–20 mA',
          summary:
            'Process automation analog current loop where 4 mA and 20 mA bracket the sensor range, and the live zero at 4 mA makes an open loop distinguishable from a real minimum reading.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'data', 'diagnostics', 'examples'],
          tools: [
            'Current→Engineering Value',
            'Engineering Value→Current',
            'Shunt Resistor Calculator',
            'ADC Voltage Calculator',
            'Compliance Voltage',
            'Cable Resistance',
            'Live Zero',
            'Sensor Range',
            'Fault Detection',
            'Trend View',
          ],
        },
      ],
    },
    {
      id: 'peripheral-buses',
      name: 'Peripheral Buses',
      summary:
        'Clocked on-board buses between a host controller and its memories, sensors and power devices — the SPI family and the I²C family.',
      protocols: [
        {
          id: 'spi',
          name: 'SPI',
          summary:
            'Four-wire clocked full-duplex bus between a host and chip-selected peripherals, where the CPOL/CPHA mode pair and bit order decide whether the same wires read sense or garbage.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'build', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'Configuration',
            'Signal View',
            'Timing Diagram',
            'Transfer Decoder',
            'Register Transaction Decoder',
            'Packet Builder',
            'Transfer Time Calculator',
            'Setup/Hold Analyzer',
            'CS Timing',
            'Throughput Calculator',
            'Error Analyzer',
          ],
        },
        {
          id: 'quad-spi',
          name: 'Quad SPI',
          summary:
            'Four-lane serial memory interface whose command, address, dummy and data phases can each use a different lane width, used for external NOR Flash and memory-mapped execution.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'timing', 'data', 'examples'],
          tools: [
            'IO0–IO3 Lane View',
            'Command Phase',
            'Address Phase',
            'Dummy Cycles',
            'Data Phase',
            'Read Transaction',
            'Write Transaction',
            'Throughput Calculator',
            'Memory Transaction Viewer',
          ],
        },
        {
          id: 'octal-spi',
          name: 'Octal SPI',
          summary:
            'Eight-lane serial memory interface with SDR/DDR transfers and a DQS strobe, used by modern external Flash and PSRAM for execute-in-place workloads.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'timing', 'data', 'examples'],
          tools: [
            'IO0–IO7 Lane View',
            'SDR Mode',
            'DDR Mode',
            'DQS View',
            'Command Phase',
            'Address Phase',
            'Dummy Cycles',
            'Data Phase',
            'XIP View',
            'Memory Transaction Analyzer',
            'Throughput Calculator',
          ],
        },
        {
          id: 'microwire',
          name: 'Microwire',
          summary:
            'Three-wire half-duplex master/slave interface found on legacy serial EEPROMs and converters, where opcode, address and word length come from the device datasheet rather than a fixed standard.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'timing', 'data', 'examples'],
          tools: [
            'Command Decoder',
            'Opcode View',
            'Address Field',
            'Data Field',
            'Read Transaction',
            'Write Transaction',
            'EEPROM Transaction View',
            'Timing Diagram',
          ],
        },
        {
          id: 'i2c',
          name: 'I²C',
          summary:
            'Two-wire open-drain addressed bus between a controller and multiple targets, where START/STOP conditions, the ACK bit and pull-up sizing govern every register transaction.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'Signal View',
            'START/STOP Detector',
            'Address Decoder',
            'Read/Write Bit',
            'ACK/NACK View',
            'Register Transaction',
            'Repeated START',
            'Clock Stretch Analyzer',
            'Arbitration Analyzer',
            'Bus Scanner',
            'Timing Calculator',
            'Pull-Up Calculator',
            'Bus Capacitance',
            'Bus Utilization',
            'Live Decoder',
            'Transaction Builder',
            'Error Analyzer',
          ],
        },
        {
          id: 'i3c',
          name: 'I3C',
          summary:
            'MIPI two-wire sensor bus that keeps legacy I²C targets on the same lines while adding dynamic addressing, common command codes, in-band interrupts and hot-join.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'data', 'diagnostics', 'examples'],
          tools: [
            'Device Discovery',
            'Static Address',
            'Dynamic Address',
            'ENTDAA Timeline',
            'CCC Commands',
            'SDR Traffic',
            'HDR Traffic',
            'IBI Analyzer',
            'Hot-Join Monitor',
            'Legacy I²C Devices',
            'Device Table',
            'Diagnostics',
          ],
        },
        {
          id: 'smbus',
          name: 'SMBus',
          summary:
            'System management bus built on I²C electricals that fixes a closed set of transaction types plus PEC error checking and explicit bus timeout behaviour.',
          layer: 'data-link',
          status: 'planned',
          tabs: ['overview', 'decode', 'build', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'Quick Command',
            'Send Byte',
            'Receive Byte',
            'Read Byte',
            'Write Byte',
            'Read Word',
            'Write Word',
            'Block Read',
            'Block Write',
            'PEC Calculator',
            'Timeout Monitor',
            'Transaction Decoder',
          ],
        },
        {
          id: 'pmbus',
          name: 'PMBus',
          summary:
            'SMBus-based command protocol for digital power devices, turning raw Linear11/Linear16/Direct words from converters and PSUs into volts, amps, degrees and fault bits.',
          layer: 'application',
          status: 'planned',
          tabs: ['overview', 'decode', 'build', 'data', 'diagnostics', 'definitions', 'examples'],
          tools: [
            'Device Explorer',
            'Command Browser',
            'READ_VOUT',
            'READ_IOUT',
            'READ_TEMPERATURE',
            'STATUS Decoder',
            'Linear11 Decoder',
            'Linear16 Decoder',
            'Direct Format Decoder',
            'Telemetry Dashboard',
            'Fault Decoder',
            'Command Builder',
          ],
          // Komut kümesi cihaz başına değişir: PMBus çekirdeği ortak, ama hangi
          // komutun hangi formatta döndüğü üreticiye ait haritadan gelir.
          definitions: ['vendor-map'],
        },
        {
          id: 'one-wire',
          name: '1-Wire',
          summary:
            'Single data line plus ground bus where reset/presence pulses, a 64-bit ROM ID per device and a search tree replace addressing, often with the device powered parasitically from the line.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'timing', 'data', 'examples'],
          tools: [
            'Reset Pulse',
            'Presence Pulse',
            'ROM Commands',
            '64-bit ROM ID Decoder',
            'Search ROM Tree',
            'Device Tree',
            'Scratchpad View',
            'Read/Write Slot',
            'Parasite Power Analyzer',
            'Timing Analyzer',
          ],
        },
      ],
    },
    {
      id: 'host-network-interfaces',
      name: 'Host & Network Interfaces',
      summary:
        'Host-side and wired-network interfaces where the toolkit stays at the enumeration, PHY and link level — packet protocols live in the Network & Ethernet domain.',
      protocols: [
        {
          id: 'usb',
          name: 'USB',
          summary:
            'Host-driven layered bus whose enumeration sequence, descriptor tree and four transfer types explain most "device not recognised" failures long before any payload is inspected.',
          layer: 'multi-layer',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'data', 'diagnostics', 'examples'],
          tools: [
            'Device Enumeration',
            'Descriptor Decoder',
            'Control Transfer',
            'Bulk Transfer',
            'Interrupt Transfer',
            'Isochronous Transfer',
            'Endpoint Explorer',
            'PID Decoder',
            'Setup Packet Decoder',
            'Error Analyzer',
          ],
        },
        {
          id: 'ethernet-interface',
          name: 'Ethernet Interface',
          summary:
            'The MAC-to-PHY side of Ethernet — link status, speed, duplex, auto-negotiation and the MII/RMII/GMII/RGMII wiring plus MDIO register access that brings a link up.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'decode', 'data', 'diagnostics', 'examples'],
          tools: [
            'Link Status',
            'PHY View',
            'Speed',
            'Duplex',
            'Auto-Negotiation',
            'MII',
            'RMII',
            'GMII',
            'RGMII',
            'MDIO/MDC Decoder',
            'PHY Register Viewer',
          ],
        },
        {
          id: 'single-pair-ethernet',
          name: 'Single Pair Ethernet',
          summary:
            'Ethernet over one balanced twisted pair (10BASE-T1S/T1L, 100BASE-T1, 1000BASE-T1), including the PLCA scheme that makes a shared multidrop segment behave deterministically.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            '10BASE-T1S',
            '10BASE-T1L',
            '100BASE-T1',
            '1000BASE-T1',
            'PLCA Analyzer',
            'PHY Configuration',
            'Link Status',
            'Diagnostics',
          ],
        },
      ],
    },
    {
      id: 'vehicle-field-physical-layers',
      name: 'Vehicle / Field Physical Layers',
      summary:
        'The transceiver-level view of the automotive buses: differential voltages, termination, topology and propagation budget, with frame decoding left to the Automotive domain.',
      protocols: [
        {
          id: 'can-phy',
          name: 'CAN PHY',
          summary:
            'ISO 11898-2 differential layer where the dominant/recessive wired-AND behaviour, 120 Ω end termination and total propagation budget set the achievable bit rate and sample point.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'CANH/CANL Signal View',
            'Differential Voltage',
            'Dominant/Recessive View',
            'Termination Calculator',
            'Split Termination',
            'Bus Topology',
            'Propagation Delay',
            'Transceiver Delay',
            'Physical Diagnostics',
          ],
        },
        {
          id: 'lin-phy',
          name: 'LIN PHY',
          summary:
            'Single-wire 12 V automotive subnet layer for low-cost switches and actuators, where break, sync and wake-up patterns sit around an otherwise UART-like byte format.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'Single-Wire Signal View',
            'Dominant/Recessive View',
            'Wake-Up Detection',
            'Break Detection',
            'Transceiver View',
            'Physical Diagnostics',
          ],
        },
        {
          id: 'flexray-phy',
          name: 'FlexRay PHY',
          summary:
            'Dual-channel differential layer for deterministic automotive networks, covering passive bus, active star and hybrid topologies plus the A/B skew that breaks redundancy.',
          layer: 'physical',
          status: 'planned',
          tabs: ['overview', 'timing', 'data', 'diagnostics', 'examples'],
          tools: [
            'Channel A View',
            'Channel B View',
            'Differential Signal View',
            'Passive Bus Topology',
            'Active Star Topology',
            'Hybrid Topology',
            'Physical Diagnostics',
          ],
        },
      ],
    },
    {
      id: 'framing-stream-protocols',
      name: 'Framing & Stream Protocols',
      summary:
        'General-purpose ways of turning a byte stream into frames — custom formats, escaping and stuffing schemes, file transfer sessions, navigation binaries and text command sets.',
      protocols: [
        {
          id: 'custom-binary-protocol',
          name: 'Custom Binary Protocol',
          summary:
            'Vendor-specific binary frame format described by the user — header, address, command, length, payload and CRC — which is what most industrial devices actually speak.',
          layer: 'data-link',
          status: 'planned',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'timing',
            'data',
            'diagnostics',
            'definitions',
            'examples',
          ],
          tools: [
            'Header Field',
            'Address Field',
            'Command Field',
            'Length Field',
            'Payload View',
            'CRC Validator',
            'Parser Builder',
            'Packet Builder',
            'Sequence Counter Tracker',
            'Request/Response Matcher',
          ],
          definitions: ['custom-schema'],
        },
        {
          id: 'ascii-protocol',
          name: 'ASCII Protocol',
          summary:
            'Human-readable line-oriented serial protocol class where CR/LF termination, numeric field parsing and echo detection decide whether a response was understood correctly.',
          layer: 'data-link',
          status: 'planned',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'timing',
            'data',
            'diagnostics',
            'definitions',
            'examples',
          ],
          tools: [
            'HEX + ASCII Dual View',
            'Line Termination Handler',
            'Command/Response Parser',
            'Numeric Field Parser',
            'Echo Detection',
            'Parser Error View',
          ],
          definitions: ['custom-schema'],
        },
        {
          id: 'delimiter-based-protocol',
          name: 'Delimiter-Based Protocol',
          summary:
            'Framing by start and end marker bytes such as STX/ETX, where the real work is handling a delimiter value that also appears inside the payload.',
          layer: 'data-link',
          status: 'planned',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'data',
            'diagnostics',
            'definitions',
            'examples',
          ],
          // Kaynak escape dönüşümünü kasıtlı olarak açık bırakıyor: tek bir
          // algoritma yeterli değil, kural kullanıcı tarafından tanımlanmalı.
          tools: [
            'Start/End Delimiter Configuration',
            'STX/ETX Framing',
            'Delimiter Collision Analyzer',
            'Escape Rule Editor',
            'Byte Stuffing View',
            'Frame Decoder',
          ],
          definitions: ['custom-schema'],
        },
        {
          id: 'length-based-protocol',
          name: 'Length-Based Protocol',
          summary:
            'Framing driven by a length field in the header, where length semantics, endianness and a maximum-frame guard separate a working parser from one that hangs on a corrupt byte.',
          layer: 'data-link',
          status: 'planned',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'data',
            'diagnostics',
            'definitions',
            'examples',
          ],
          tools: [
            'Length Field Configuration',
            'Length Semantics Selector',
            'Endianness Selector',
            'Maximum Frame Length Guard',
            'Resynchronization Analyzer',
            'Frame Decoder',
            'Checksum/CRC Validator',
          ],
          definitions: ['custom-schema'],
        },
        {
          id: 'slip',
          name: 'SLIP',
          summary:
            'RFC 1055 framing that wraps IP datagrams on a serial line using END and ESC bytes only, deliberately providing no addressing, no length and no integrity check.',
          layer: 'data-link',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'diagnostics', 'examples'],
          tools: [
            'SLIP Encoder',
            'SLIP Decoder',
            'Escape View',
            'END/ESC Byte Map',
            'Decoder State Machine',
          ],
        },
        {
          id: 'cobs',
          name: 'COBS',
          summary:
            'Reversible byte stuffing that removes every zero byte from a frame so 0x00 can serve as an unambiguous delimiter, at a worst case of one extra byte per 254.',
          layer: 'data-link',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'diagnostics', 'examples'],
          tools: [
            'COBS Encoder',
            'COBS Decoder',
            'Overhead Calculator',
            'Code Byte View',
            'Zero Delimiter View',
            'COBS + CRC Pipeline',
          ],
        },
        {
          id: 'hdlc',
          name: 'HDLC',
          summary:
            'Bit-oriented data-link framing with a 0x7E flag, five-ones bit stuffing and an I/S/U control field, forming the base of PPP, SDLC and many telecom links.',
          layer: 'data-link',
          status: 'planned',
          // 'live' yok: bit-senkron çerçeveleme sıradan seri portla yakalanamaz,
          // ilk sürüm log/import üzerinden çalışır.
          tabs: ['overview', 'decode', 'build', 'data', 'diagnostics', 'examples'],
          tools: [
            'Flag Detector',
            'Bit Stuffing View',
            'Address Field',
            'Control Field Decoder',
            'I/S/U Frame Classifier',
            'Information Field',
            'FCS Validator',
            'Transmitted Bit Stream View',
          ],
        },
        {
          id: 'sdlc',
          name: 'SDLC',
          summary:
            "IBM's synchronous bit-oriented predecessor of HDLC, built around primary/secondary stations, station addressing and poll/final signalling in legacy mainframe links.",
          layer: 'data-link',
          status: 'planned',
          tabs: ['overview', 'decode', 'build', 'data', 'diagnostics', 'examples'],
          tools: [
            'Flag Detector',
            'Station Address Decoder',
            'Control Field Decoder',
            'Information/Supervisory/Unnumbered Classifier',
            'Poll/Final State',
            'Bit Stuffing View',
            'FCS Validator',
            'Station Model',
          ],
        },
        {
          id: 'ppp',
          name: 'PPP',
          summary:
            'RFC 1661 encapsulation that carries several network-layer protocols over one point-to-point link, negotiated by LCP and framed HDLC-style with 0x7D escaping and an ACCM.',
          layer: 'data-link',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'data', 'diagnostics', 'examples'],
          tools: [
            'PPP Frame Decoder',
            'Protocol Field Decoder',
            'LCP Code Decoder',
            'Negotiation Timeline',
            'Asynchronous Escaping View',
            'ACCM Viewer',
            'FCS Validator',
          ],
        },
        {
          id: 'kiss',
          name: 'KISS',
          summary:
            'Minimal FEND-delimited framing between a computer and a packet-radio TNC, whose payload is normally an AX.25 frame that can be decoded further up the chain.',
          layer: 'data-link',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'diagnostics', 'examples'],
          tools: [
            'FEND Framing',
            'FESC Escaping View',
            'Command/Port Decoder',
            'KISS Decoder',
            'KISS Encoder',
            'AX.25 Chain Decode',
            'Error View',
          ],
        },
        {
          id: 'xmodem',
          name: 'XMODEM',
          summary:
            'Stop-and-wait serial file transfer in 128- or 1024-byte blocks with block-number complement checking, checksum or CRC-16 mode, and NAK-driven retransmission.',
          layer: 'application',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'timing', 'diagnostics', 'examples'],
          tools: [
            'Transfer Session View',
            'Block Decoder',
            'Block Number / Complement Check',
            'Checksum Calculator',
            'CRC-16 Mode Handshake',
            'ACK/NAK Timeline',
            'Retry Analyzer',
            'Progress View',
          ],
        },
        {
          id: 'ymodem',
          name: 'YMODEM',
          summary:
            'XMODEM extended with a block 0 metadata header carrying filename, size and modification time, enabling batch transfer of several files in one session.',
          layer: 'application',
          status: 'planned',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'timing',
            'data',
            'diagnostics',
            'examples',
          ],
          tools: [
            'Transfer Session View',
            'Block 0 Metadata Decoder',
            'Filename / Filesize Parser',
            'Modification Time Decoder',
            '128/1024 Sector Handling',
            'Batch Session Tree',
            'CRC Validator',
            'ACK/NAK Timeline',
            'Retry Analyzer',
            'Progress View',
          ],
        },
        {
          id: 'zmodem',
          name: 'ZMODEM',
          summary:
            'Streaming file transfer with position-based error recovery and resume, exchanging ZRQINIT/ZRINIT/ZFILE/ZRPOS/ZDATA/ZEOF/ZFIN frames instead of waiting for a per-block ACK.',
          layer: 'application',
          status: 'planned',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'timing',
            'data',
            'diagnostics',
            'examples',
          ],
          // Kanonik tek bir ZMODEM yok; parser hangi implementasyon profiline
          // göre çözdüğünü metadata olarak taşımalı.
          tools: [
            'Session State Machine',
            'ZRQINIT/ZRINIT Negotiation',
            'ZFILE Information Decoder',
            'ZDATA Streaming View',
            'ZRPOS Position / Resume Analyzer',
            'Error Recovery View',
            'Batch Transfer Tree',
            'CRC Validator',
            'Implementation Profile Metadata',
          ],
        },
        {
          id: 'ubx',
          name: 'UBX',
          summary:
            'u-blox binary GNSS message format with a B5 62 sync, class/ID naming and a two-byte checksum, usually interleaved with NMEA and RTCM on the same receiver port.',
          layer: 'application',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'data', 'diagnostics', 'examples'],
          tools: [
            'Sync/Class/ID/Length Frame View',
            'Class-ID Browser',
            'Little-Endian Length Decoder',
            'Payload Decoder',
            'Checksum Validator',
            'Packet Builder',
            'Multi-Protocol Stream Detector',
          ],
          related: ['interfaces-framing/framing-stream-protocols/rtcm'],
          aliasOf: 'marine-navigation/gnss-corrections/gnss-ubx',
        },
        {
          id: 'rtcm',
          name: 'RTCM',
          summary:
            'GNSS correction message family framed by a 0xD3 preamble, length and CRC, carrying reference station, observation, MSM and SSR message types to RTK rovers.',
          layer: 'application',
          status: 'planned',
          // 'build' yok: tam mesaj tabloları lisanslı yayın kapsamında olduğu için
          // güvenilir bir üretici (encoder) açık kaynaklarla kurulamaz.
          tabs: ['overview', 'live', 'decode', 'data', 'diagnostics', 'examples'],
          tools: [
            'Preamble/Length/Payload/CRC Frame View',
            'Message Type Decoder',
            'Station ID Decoder',
            'RTCM 2.x / 3.x Version Selector',
            'Message Database Browser',
            'CRC Validator',
            'Multi-Protocol GNSS Monitor',
          ],
          related: ['interfaces-framing/framing-stream-protocols/ubx'],
          aliasOf: 'marine-navigation/gnss-corrections/rtcm',
        },
        {
          id: 'at-commands',
          name: 'AT Commands',
          summary:
            'ITU-T V.250 and 3GPP TS 27.007 text command set for modems and cellular modules, where unsolicited result codes must be kept on a separate channel from command responses.',
          layer: 'application',
          // Faz 10 dalga 9b: jenerik çerçeveleme motoru yazıldı
          // (src/protocols/serial/atcommands/atCommands.ts) — komut/yanıt
          // ayrımı, URC, final result code (OK/ERROR/+CME ERROR/+CMS ERROR).
          // hayes-command-set BU sayfada değil, kendi (planned) kaydında —
          // motoru nasıl kullanacağı ayrı bir karar (brief 9b madde 7).
          status: 'ready',
          pluginId: 'at-commands',
          tabs: [
            'overview',
            'live',
            'decode',
            'build',
            'timing',
            'data',
            'diagnostics',
            'examples',
          ],
          tools: [
            'Command Parser',
            'Response Parser',
            'URC Stream Separator',
            'Parser State Machine',
            'Command Console',
            'Final Result Code Decoder',
            'Prompt / Binary Payload Handler',
            'Response Time Measurement',
          ],
        },
        {
          id: 'hayes-command-set',
          name: 'Hayes Command Set',
          summary:
            'The original ATtention command vocabulary — ATD, ATA, ATH, ATZ, S-registers and the guard-timed +++ escape that separates command mode from online data mode.',
          layer: 'application',
          status: 'planned',
          tabs: ['overview', 'live', 'decode', 'build', 'data', 'diagnostics', 'examples'],
          // "+++" tespiti üç artı aramak DEĞİLDİR: guard-time olmadan veri
          // içindeki literal "+++" yanlış pozitif üretir.
          tools: [
            'Basic Command Decoder',
            'Dial Command Parser',
            'S-Register Browser',
            'Result Code Mapper',
            'Command / Data Mode State View',
            'Escape Sequence Guard-Time Analyzer',
            'Echo / Verbose Detection',
          ],
        },
      ],
    },
  ],
};
