/**
 * Örnek XIF dosyaları — `edsFixture.ts` ile aynı rol: hem testlerin çıpası hem
 * arayüzün açılış içeriği, böylece ekran BOŞ AÇILMAZ (spec §50) ve ekranda
 * çalışan örnek testte de yeşildir.
 *
 * ── ⚠ FIXTURE UYDURULMADI, AMA KAYNAĞI BRİFTEKİ DEĞİL ───────────────────────
 * Brif fixture'ın `izot/shortstack`ten gelmesini istiyordu. Depo GERÇEKTEN
 * açıldı ve içindeki **20 `.xif` dosyasının hepsi** okundu; hiçbiri bu iş için
 * kullanılamaz ve sebep ÖLÇÜLDÜ: hepsi ShortStack **microserver** arayüz
 * dosyasıdır ve hepsinde başlık satır 6 alan 4 (statik NV bildirimi sayısı)
 * **0**'dır — yani sıfır network variable taşırlar. Bir NV tablosunu
 * kanıtlaması gereken panelin açılış örneği olamazlardı.
 *
 * Bunun yerine `SAMPLE_XIF_TEXT` **gerçek bir saha cihazının** üreticisi
 * tarafından yayımlanmış XIF'idir: Continental Control Systems, LLC'nin
 * WattNode güç/enerji ölçerinin `WNC-FT-B-303.XIF` dosyası
 * (`ctlsys.com/support/external_interface_files_xif/`, girişsiz indirme).
 * Biçim sürümü 4.400, 28 network variable, 6'sı konfigürasyon sınıfı. İçerik
 * **KISALTILMADI ve DEĞİŞTİRİLMEDİ** — yalnız satır sonları CRLF'ten LF'e
 * çevrildi. Kısaltmak başlığın bildirdiği 28 sayısıyla dosyadaki kayıt sayısını
 * ayrıştırırdı ve panel gerçekte var olmayan bir uyuşmazlık uyarısı basardı.
 *
 * `SAMPLE_MICROSERVER_XIF_TEXT` ise `izot/shortstack`ten GERÇEKTEN alındı
 * (`microserver/standard/SS430_FT6050_SYS20000kHz.xif`) ve bir teste hizmet
 * ediyor: sıfır NV taşıyan bir XIF GEÇERLİDİR ve `success: false` DÖNMEMELİDİR
 * (`xifTypes.ts`teki `XifParseResult` gerekçesi bu dosyayla ölçüldü).
 *
 * ── DALGA 17 İLE BAĞLANTI ───────────────────────────────────────────────────
 * `lonworks.ts` NV mesajının yalnız 14 bitlik bir selector taşıdığını, SNVT
 * tipinin telde OLMADIĞINI söylüyor (`nvTypeNotOnWire`). Bu dosya tam olarak o
 * boşluğun ÖTEKİ yarısıdır: tip bilgisinin nerede YAŞADIĞI. İkisi birlikte
 * okunmalı — XIF tipi SÖYLER, tel DOĞRULAMAZ.
 */

/** `WNC-FT-B-303.XIF`in program ID'si — cihazın kendi bildirimi. */
export const SAMPLE_XIF_PROGRAM_ID = '80:00:22:15:00:0A:04:05';
/** Başlık satır 6 alan 4'ün bildirdiği ve dosyada gerçekten bulunan NV sayısı. */
export const SAMPLE_XIF_NV_COUNT = 28;
/** Satır 2 alan 13'ü set olan NV sayısı — CPNV olarak gerçeklenen config property'ler. */
export const SAMPLE_XIF_CONFIG_PROPERTY_COUNT = 6;
/** `nvoStatus` — 26 elemanlı bir YAPI; SNVT #93 skaler tablonun DIŞINDADIR. */
export const SAMPLE_XIF_STATUS_NV_INDEX = 1;
/** `nciDemPerMins` — konfigürasyon sınıfı, tek elemanlı, SNVT #8 (`SNVT_count`). */
export const SAMPLE_XIF_DEMAND_PERIOD_NV_INDEX = 38;

export const SAMPLE_XIF_TEXT = `File: WNC-FT-B-303.XIF generated by LONNCC32 Version 4.04.12, XIF Version 4.400
Copyright (c) Echelon Corporation 1989-2007
All Rights Reserved.  Run on Mon Mar 30 22:33:36 2009

80:00:22:15:00:0A:04:05
2 15 1 28 0 3 4 0 0 4 4 11 11 9 10 0 0 8 5 1 1 128 28 0 0 0 0 0 0 0 0 0 2 15 0 0 0 0 0 2 1 0
0 5 16 13 28 738 0 15 5 3 257 4 10000000
1 7 1 1 4 4 4 15 200 0
78125 0 0 0 0 0 164 0 0 0 0 0
90 0 240 0 0 0 40 40 0 5 8 5 12 14 15
*
"WattNode Power/Energy Sensor

VAR nviRequest 0 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 0
"Object request (object_id,request)
92 *   2
2 0 0 0 0
1 0 0 1 0
VAR nvoStatus 1 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Object status
93 *  26
2 0 0 0 0
3 0 1 0 0
3 1 1 0 0
3 2 1 0 0
3 3 1 0 0
3 4 1 0 0
3 5 1 0 0
3 6 1 0 0
3 7 1 0 0
3 0 1 0 0
3 1 1 0 0
3 2 1 0 0
3 3 1 0 0
3 4 1 0 0
3 5 1 0 0
3 6 1 0 0
3 7 1 0 0
3 0 1 0 0
3 1 1 0 0
3 2 1 0 0
3 3 1 0 0
3 4 1 0 0
3 5 1 0 0
3 6 1 0 0
3 7 1 0 0
3 0 8 0 0
VAR nviTimeSet 2 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 0
"Time of day (yr,mn,dy,hr,mn,sec)
84 *   6
2 0 0 1 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
VAR nviCalSel 3 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 0
"Calibration variable selector
8 *   1
2 0 0 0 0
VAR nviCal 4 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 0
"Calibration variable value
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoPowerSum 5 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Total real power (watts)
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoPower 6 0 0 3
0 1 63 1 0 1 0 1 0 0 0 0 0
"Individual phase real power
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nciCtAmps_f 9 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 1
"Current transformer rated amps
48 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nciPwrUpdtT 10 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 1
"Time between power variable updates
87 *   5
2 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
2 0 0 0 0
VAR nvoEnergySum 11 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Total real energy (watt-hours)
68 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoEnergy 12 0 0 3
0 1 63 1 0 1 0 1 0 0 0 0 0
"Individual phase real energy
68 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nciEngyUpdtT 15 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 1
"Time between energy variable updates
87 *   5
2 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
2 0 0 0 0
VAR nvoPFavg 16 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Average power factor for the load
99 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoPF 17 0 0 3
0 1 63 1 0 1 0 1 0 0 0 0 0
"Individual phase power factor
99 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoReacPwrSum 20 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Total reactive power (watts)
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoReacPwr 21 0 0 3
0 1 63 1 0 1 0 1 0 0 0 0 0
"Individual phase reactive power
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nciReacUpdtT 24 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 1
"Time between reactive variable updates
87 *   5
2 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
2 0 0 0 0
VAR nvoReacEngySum 25 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Total reactive energy (watt-hours)
68 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoVolts 26 0 0 3
0 1 63 1 0 1 0 1 0 0 0 0 0
"Voltage
66 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoCurrent 29 0 0 3
0 1 63 1 0 1 0 1 0 0 0 0 0
"Current
48 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoFreq 32 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Line frequency
75 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoDemand 33 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Demand power (watts)
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoPkDemand 34 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Peak demand
57 *   5
3 0 1 0 0
3 1 7 0 0
3 0 1 0 0
3 1 7 0 0
2 0 0 0 0
VAR nvoPeakDemT 35 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Peak demand time
84 *   6
2 0 0 1 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
1 0 0 0 0
VAR nviLogRequest 36 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 0
"Demand log request (1=current record, 2=previous record)
8 *   1
2 0 0 0 0
VAR nvoLogData 37 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
"Demand log data
36 *   1
0 0 0 0 31
VAR nciDemPerMins 38 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 1
"Demand period: 5-720 minutes
8 *   1
2 0 0 0 0
VAR nciDemSubints 39 0 0 0
0 1 63 0 0 1 0 1 0 0 0 0 1
"Demand subintervals (1 to 8)
8 *   1
2 0 0 0 0
`;

/**
 * `izot/shortstack`ın microserver arayüz dosyası — GERÇEK, değiştirilmemiş.
 * Sıfır NV taşır ve bu bir hata DEĞİLDİR: rehberin kendi cümlesi *"All sections
 * are optional, except for the header section."*
 */
export const SAMPLE_MICROSERVER_XIF_TEXT = `File: _MicroServer.XIF generated by LONNCC32 Version 6.40.02, XIF Version 4.501
Copyright (c) Echelon Corporation 1989-2015
All Rights Reserved.  Run on Tue Aug 18 09:23:42 2015

53:34:33:30:30:42:42:30
2 15 1 0 0 6 6 4 4 6 6 14 14 14 14 7 254 16 127 0 1 11 0 0 0 0 0 0 0 0 0 0 2 15 0 0 0 0 0 2 609 0 0 32 0
36 6 21 15 68 1194 4234 15 5 4 1842 5 10000000 1
1 7 1 1 4 4 4 15 200 0
78125 0 0 0 0 0 252 0 0 0 0 0
90 0 240 0 0 0 40 40 0 5 22 9 26 43 44
*
*

`;
