import { describe, expect, it } from 'vitest';

import {
  SAMPLE_MICROSERVER_XIF_TEXT,
  SAMPLE_XIF_CONFIG_PROPERTY_COUNT,
  SAMPLE_XIF_DEMAND_PERIOD_NV_INDEX,
  SAMPLE_XIF_NV_COUNT,
  SAMPLE_XIF_PROGRAM_ID,
  SAMPLE_XIF_STATUS_NV_INDEX,
  SAMPLE_XIF_TEXT,
} from './xifFixture';
import { findXifNetworkVariable, parseXif, selectXifConfigProperties } from './xifParser';
import type { XifParseResult } from './xifTypes';

function expectSuccess(result: XifParseResult): Extract<XifParseResult, { success: true }> {
  if (!result.success) {
    throw new Error(`expected success, got issues: ${result.issues.map((i) => i.messageKey).join(', ')}`);
  }
  return result;
}

/**
 * KURULMUŞ test girdisi — bir cihaz dosyası DEĞİL. Başlığı en az sayıda alanla
 * kurulmuş, KAYIT gövdeleri ise LONMARK rehberinin (rev 4.501) kendi yayımlanmış
 * örneklerinden BİREBİR alınmıştır. Fixture'lar gerçek dosyadır (`xifFixture.ts`);
 * burada amaç rehberin tarif ettiği ama WattNode dosyasında BULUNMAYAN bölümleri
 * (TAG · FILE · NVVAL · yapı elemanları) sınamaktır.
 */
function buildHeader(staticNvCount: number, messageTagCount = 0): string {
  return [
    'File: TEST.XIF generated by Manual 0.0.0, XIF Version 4.501',
    'Copyright (c) test',
    'All Rights Reserved.  Run on Mon Jan 01 00:00:00 2024',
    '',
    '9F:FF:FF:05:01:84:04:65',
    `2 15 1 ${String(staticNvCount)} ${String(messageTagCount)} 4 2 0 0 2 4 0 0 0 0 7 0 13 17 1 1 11`,
    '36 6 21 15 43 1176 2614 15 5 4 279 5 10000000 1',
    '1 7 1 1 4 4 4 15 200 0',
    '78125 0 0 0 0 0 252 0 0 0 0 0',
    '90 0 240 0 0 0 40 40 0 5 22 9 26 43 44',
    '*',
    '*',
    '',
  ].join('\n');
}

describe('parseXif — gerçek cihaz dosyası (WattNode WNC-FT-B-303)', () => {
  it('başlığın 1. satırından dosya adını, aracı ve biçim sürümünü çözer', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    expect(database.fileInfo.fileName).toBe('WNC-FT-B-303.XIF');
    expect(database.fileInfo.generatedBy).toBe('LONNCC32 Version 4.04.12');
    expect(database.fileInfo.formatVersion).toBe('4.400');
    expect(database.fileInfo.formatMajor).toBe(4);
    expect(database.fileInfo.formatMinor).toBe(400);
    expect(database.fileInfo.timestamp).toBe('Mon Mar 30 22:33:36 2009');
  });

  it('program ID ve cihaz self-documentation metnini çözer', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    expect(database.device.programId).toBe(SAMPLE_XIF_PROGRAM_ID);
    expect(database.device.selfDocumentation).toBe('WattNode Power/Energy Sensor');
  });

  it('başlığın sayısal alanlarını KONUMLA değil ÇAPAYLA bulur', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    expect(database.device.domainCount).toBe(2);
    expect(database.device.addressTableEntries).toBe(15);
    expect(database.device.declaredStaticNvCount).toBe(SAMPLE_XIF_NV_COUNT);
    expect(database.device.declaredMessageTagCount).toBe(0);
    // Satır 9 alan 1 — FT-10 kanalının 78125 bit/s'i.
    expect(database.device.channelBitRate).toBe(78125);
  });

  it('28 network variable çıkarır ve hiç uyarı üretmez', () => {
    const { database, issues } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    expect(database.networkVariables).toHaveLength(SAMPLE_XIF_NV_COUNT);
    expect(issues).toEqual([]);
  });

  it('bildirilen NV sayısı ile bulunan kayıt sayısı tutar — uyuşmazlık uyarısı YOK', () => {
    const { database, issues } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    expect(database.device.declaredStaticNvCount).toBe(database.networkVariables.length);
    expect(issues.map((issue) => issue.messageKey)).not.toContain(
      'definition.xif.issue.nvCountMismatch',
    );
  });

  it('yapı tipli bir NV nin bütün elemanlarını okur (nvoStatus, 26 eleman)', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    const status = findXifNetworkVariable(database, SAMPLE_XIF_STATUS_NV_INDEX);
    expect(status?.name).toBe('nvoStatus');
    expect(status?.direction).toBe('output');
    expect(status?.configClass).toBe(false);
    expect(status?.snvtIndex).toBe(93);
    expect(status?.elementCount).toBe(26);
    expect(status?.elements).toHaveLength(26);
    expect(status?.selfDocumentation).toBe('Object status');
    // İlk eleman 16-bit int (kod 2), ikinci eleman bitfield (kod 3).
    expect(status?.elements[0]?.type).toBe(2);
    expect(status?.elements[1]).toEqual({ type: 3, bitOffset: 0, size: 1, signed: false, arraySize: 0 });
  });

  it('konfigürasyon sınıfı NV yi (CPNV) ayırt eder', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    const demandPeriod = findXifNetworkVariable(database, SAMPLE_XIF_DEMAND_PERIOD_NV_INDEX);
    expect(demandPeriod?.name).toBe('nciDemPerMins');
    expect(demandPeriod?.configClass).toBe(true);
    expect(demandPeriod?.direction).toBe('input');
    expect(demandPeriod?.snvtIndex).toBe(8);
    expect(demandPeriod?.elementCount).toBe(1);
  });

  it('selectXifConfigProperties altı CPNV döndürür', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    const properties = selectXifConfigProperties(database);
    expect(properties).toHaveLength(SAMPLE_XIF_CONFIG_PROPERTY_COUNT);
    expect(properties.every((property) => property.configClass)).toBe(true);
    expect(properties.map((property) => property.name)).toEqual([
      'nciCtAmps_f',
      'nciPwrUpdtT',
      'nciEngyUpdtT',
      'nciReacUpdtT',
      'nciDemPerMins',
      'nciDemSubints',
    ]);
  });

  it('dosya NVVAL taşımadığı için hiçbir CPNV varsayılan değer TAŞIMAZ', () => {
    const { database } = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    expect(selectXifConfigProperties(database).every((p) => p.defaultValue === undefined)).toBe(true);
  });

  it('CRLF satır sonu sonucu DEĞİŞTİRMEZ (gerçek dosya CRLF ile dağıtılıyor)', () => {
    const lf = expectSuccess(parseXif(SAMPLE_XIF_TEXT));
    const crlf = expectSuccess(parseXif(SAMPLE_XIF_TEXT.replace(/\n/g, '\r\n')));
    expect(crlf.database).toEqual(lf.database);
    expect(crlf.issues).toEqual(lf.issues);
  });
});

describe('parseXif — sıfır NV taşıyan GERÇEK dosya (izot/shortstack microserver)', () => {
  it('başarısız SAYILMAZ: başlık XIF in tek zorunlu bölümüdür', () => {
    const { database, issues } = expectSuccess(parseXif(SAMPLE_MICROSERVER_XIF_TEXT));
    expect(database.networkVariables).toHaveLength(0);
    expect(database.device.declaredStaticNvCount).toBe(0);
    expect(database.device.programId).toBe('53:34:33:30:30:42:42:30');
    // Bildirilen 0, bulunan 0 — uyuşmazlık uyarısı da ÇIKMAMALI.
    expect(issues).toEqual([]);
  });
});

describe('parseXif — LONMARK rehberinin kendi örnek kayıtları', () => {
  it('yapı/union NV örneğini (rehber Örnek 3, ingroup) alan alan çözer', () => {
    const text = `${buildHeader(1)}VAR ingroup 2 0 0 0
0 1 63 0 0 1 0 1 0 1 0 0 0
*
0 *   6
1 0 0 1 0
2 0 0 1 0
1 0 0 1 5
3 0 3 0 0
3 3 5 0 0
4 0 1 0 0
`;
    const { database } = expectSuccess(parseXif(text));
    const variable = database.networkVariables[0];
    expect(variable?.name).toBe('ingroup');
    expect(variable?.index).toBe(2);
    expect(variable?.direction).toBe('input');
    // Rehberin Neuron C kaynağı `network input group ingroup;` — `sync` YOK.
    expect(variable?.synchronized).toBe(false);
    expect(variable?.configClass).toBe(false);
    // snvtIndex 0 = kullanıcı tanımlı tip (UNVT).
    expect(variable?.snvtIndex).toBe(0);
    expect(variable?.elements).toHaveLength(6);
    // `int array[5]` → 8-bit int, dizi boyu 5.
    expect(variable?.elements[2]).toEqual({ type: 1, bitOffset: 0, size: 0, signed: true, arraySize: 5 });
    // `unsigned zz : 5` → bitfield, ofset 3, 5 bit.
    expect(variable?.elements[4]).toEqual({ type: 3, bitOffset: 3, size: 5, signed: false, arraySize: 0 });
    // `union u` → kod 4, 1 bayt.
    expect(variable?.elements[5]?.type).toBe(4);
  });

  it('çıkış NV örneğini (rehber Örnek 1, outvar) ve hız kodlarını çözer', () => {
    const text = `${buildHeader(1)}VAR outvar 0 69 76 0
1 1 63 1 0 0 1 0 1 0 1 0 0
*
0 *   1
2 0 0 1 0
`;
    const { database } = expectSuccess(parseXif(text));
    const variable = database.networkVariables[0];
    expect(variable?.direction).toBe('output');
    expect(variable?.takeOfflineToUpdate).toBe(true);
    expect(variable?.avgRateEncoded).toBe(69);
    expect(variable?.maxRateEncoded).toBe(76);
    expect(variable?.serviceType).toBe('acknowledged');
    expect(variable?.serviceTypeConfigurable).toBe(false);
    expect(variable?.authenticated).toBe(true);
    expect(variable?.priority).toBe(true);
    expect(variable?.polled).toBe(true);
  });

  it('sync + config bayraklarını çözer (rehber Örnek 2, invar)', () => {
    // Neuron C kaynağı: `network input sync config int invar;` — satır 2'nin
    // 12. alanı (sync) ve 13. alanı (config) İKİSİ DE 1.
    const text = `${buildHeader(1)}VAR invar 1 0 0 0
0 1 63 0 0 1 0 1 0 1 0 1 1
*
0 *   1
1 0 0 1 0
`;
    const { database } = expectSuccess(parseXif(text));
    const variable = database.networkVariables[0];
    expect(variable?.name).toBe('invar');
    expect(variable?.direction).toBe('input');
    expect(variable?.synchronized).toBe(true);
    expect(variable?.configClass).toBe(true);
    expect(variable?.elements[0]).toEqual({ type: 1, bitOffset: 0, size: 0, signed: true, arraySize: 0 });
  });

  it('message tag örneğini (rehber, user_tag) çözer', () => {
    const text = `${buildHeader(0, 1)}TAG user_tag 0 69 76 0
0 1 63 1 0 1 0 1 0 1 0 0 0
`;
    const { database, issues } = expectSuccess(parseXif(text));
    expect(database.messageTags).toEqual([
      { name: 'user_tag', index: 0, avgRateEncoded: 69, maxRateEncoded: 76, bindable: true, line: 13 },
    ]);
    expect(issues).toEqual([]);
  });

  it('NVVAL varsayılanlarını konfigürasyon NV lerine BİLDİRİM SIRASIYLA bağlar', () => {
    // Rehberin NVVAL örneği: configNv1 = 5000 (0x1388), configNv2 = 100 (0x64),
    // configNv3 = 2252 (0x08CC). Değerler ARİTMETİK olarak kendini doğruluyor.
    const configVar = (name: string, index: number): string =>
      `VAR ${name} ${String(index)} 0 0 0\n0 1 63 0 0 1 0 1 0 1 0 0 1\n*\n8 *   1\n2 0 0 0 0\n`;
    const text = `${buildHeader(3)}${configVar('configNv1', 0)}${configVar('configNv2', 1)}${configVar('configNv3', 2)}
NVVAL
# config network input long configNv1 = {5000};
0x13, 0x88
# config network input int configNv2 = {100};
0x64
# config network input long configNv3 = {2252};
0x08, 0xCC

`;
    const { database, issues } = expectSuccess(parseXif(text));
    const values = selectXifConfigProperties(database).map((property) => property.defaultValue);
    expect(values).toEqual([[0x13, 0x88], [0x64], [0x08, 0xcc]]);
    expect(issues).toEqual([]);
  });

  it('FILE kaydını okur ve içeriğin BEŞ eşdeğer hex biçimini aynı bayta çözer', () => {
    // Rehberin kendi listesi: bu beş satır aynı dört baytı (0x0789ABCD) üretir.
    const forms = ['0x07, 0x89, 0xAB, 0xCD', '0x0789abcd', '0789abcd', '7,89,ab,cd', '\\x07\\x89\\xab\\xcd'];
    for (const form of forms) {
      const text = `${buildHeader(0)}FILE cpTemplate 0 2 4
${form}

`;
      const { database } = expectSuccess(parseXif(text));
      expect(database.configFiles[0]?.name, form).toBe('cpTemplate');
      expect(database.configFiles[0]?.index, form).toBe(0);
      expect(database.configFiles[0]?.type, form).toBe(2);
      expect(database.configFiles[0]?.declaredLength, form).toBe(4);
      expect(database.configFiles[0]?.contents, form).toEqual([0x07, 0x89, 0xab, 0xcd]);
    }
  });

  it('FILE içeriğinin KARAKTER biçimini okur; ikinci tırnak dizeyi bitirir', () => {
    const text = `${buildHeader(0)}FILE cpValue 1 1
"AB"ignored
`;
    const { database } = expectSuccess(parseXif(text));
    expect(database.configFiles[0]?.contents).toEqual([0x41, 0x42]);
    expect(database.configFiles[0]?.declaredLength).toBeUndefined();
  });
});

describe('parseXif — hoşgörü ve hata dalları', () => {
  it('boş girdi başarısızdır', () => {
    const result = parseXif('   \n\n');
    expect(result.success).toBe(false);
    expect(result.issues.map((issue) => issue.messageKey)).toEqual(['definition.xif.issue.emptyInput']);
  });

  it('program ID satırı yoksa BAŞARISIZ — gösterilecek cihaz yok', () => {
    const result = parseXif('File: X.XIF generated by Manual 0.0.0, XIF Version 4.501\nCopyright\n');
    expect(result.success).toBe(false);
    expect(result.issues.map((issue) => issue.messageKey)).toContain('definition.xif.issue.noHeader');
  });

  it('1. satır söz dizimine uymuyorsa UYARIR ama dosyayı reddetmez', () => {
    const text = buildHeader(0).replace(
      'File: TEST.XIF generated by Manual 0.0.0, XIF Version 4.501',
      'Bozuk baslik satiri',
    );
    const { database, issues } = expectSuccess(parseXif(text));
    expect(issues.map((issue) => issue.messageKey)).toContain(
      'definition.xif.issue.malformedFileLine',
    );
    expect(database.device.programId).toBe('9F:FF:FF:05:01:84:04:65');
  });

  it('tanınmayan kaydı bir sonraki BOŞ SATIRA kadar atlar ve TEK uyarı basar', () => {
    const text = `${buildHeader(1)}FUTURE something 1 2 3
more future content
still future

VAR realVar 0 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
*
8 *   1
2 0 0 0 0
`;
    const { database, issues } = expectSuccess(parseXif(text));
    expect(database.networkVariables.map((variable) => variable.name)).toEqual(['realVar']);
    expect(issues.filter((issue) => issue.messageKey === 'definition.xif.issue.unknownRecord')).toHaveLength(1);
  });

  it('bildirilen NV sayısı bulunanla tutmuyorsa uyarır ama veriyi verir', () => {
    const text = `${buildHeader(5)}VAR onlyOne 0 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
*
8 *   1
2 0 0 0 0
`;
    const { database, issues } = expectSuccess(parseXif(text));
    expect(database.networkVariables).toHaveLength(1);
    const mismatch = issues.find((issue) => issue.messageKey === 'definition.xif.issue.nvCountMismatch');
    expect(mismatch?.text).toBe('5 / 1');
  });

  it('yarım kalan VAR kaydında fırlatmaz, uyarı üretir', () => {
    const text = `${buildHeader(1)}VAR truncated 0 0 0 0
`;
    const { issues } = expectSuccess(parseXif(text));
    expect(issues.map((issue) => issue.messageKey)).toContain('definition.xif.issue.truncatedRecord');
  });

  it('# ile başlayan satır her yerde yok sayılır, boş satır SAYILMAZ', () => {
    const text = `${buildHeader(1)}# bu bir yorum
VAR commented 0 0 0 0
0 1 63 1 0 1 0 1 0 0 0 0 0
*
8 *   1
2 0 0 0 0
`;
    const { database, issues } = expectSuccess(parseXif(text));
    expect(database.networkVariables.map((variable) => variable.name)).toEqual(['commented']);
    expect(issues).toEqual([]);
  });

  it('3.0 öncesi başlıkta satır 8-10 yoktur; kanal bit hızı UYDURULMAZ', () => {
    const text = [
      'File: OLD.XIF generated by Manual 0.0.0, XIF Version 2.0',
      'Copyright',
      'All Rights Reserved.  Run on Mon Jan 01 00:00:00 1996',
      '',
      '9F:FF:FF:05:01:84:04:65',
      '2 15 1 0 0 4 2 0 0 2 4 0 0 0 0',
      '36 6 21 15 43 1176 2614 15 5 4 279 5 10000000 1',
      '*',
      '*',
      '',
    ].join('\n');
    const { database } = expectSuccess(parseXif(text));
    expect(database.device.channelBitRate).toBeUndefined();
    expect(database.device.domainCount).toBe(2);
    expect(database.device.declaredStaticNvCount).toBe(0);
  });
});
