/**
 * XIF metin çözümleyicisi — `.xif` dosyası → `XifDatabase`.
 *
 * `edsParser.ts`in HOŞGÖRÜLÜ deseninin karşılığı: tanımadığı kaydı yok sayıp
 * uyarı üretir, dosyayı reddetmez (spec §47 "hatalı veride uygulamayı
 * çökertme").
 *
 * ── NEDEN SABİT SATIR ATLAMA YOK ────────────────────────────────────────────
 * `g3gg0/LonScan` başlığı `for (line = 6; line < 11) ReadLine()` diye geçiyor
 * ve kendi notuna göre bu kırılgan. ÖLÇÜLEBİLİR sebebi şu: rehberin kendi
 * sürüm tablosuna göre başlığın 8, 9 ve 10. satırları YALNIZ 3.0 ve sonrasında
 * vardır, 2.x dosyalarında satır 8'in yerinde `*` durur. Sabit sayıyla atlayan
 * bir okuyucu böyle bir dosyada üç satır kayar ve HATA VERMEDEN yanlış NV
 * listesi üretir.
 *
 * Bunun yerine başlık ÇAPALARLA bulunur:
 *   · program ID satırı — sekiz iki-haneli hex, iki nokta üst üste ayraçlı;
 *   · ondan sonraki SAYISAL parametre satırları, `*` görülene dek (rehber
 *     satır 11: *"a single asterisk indicating the end of the transceiver
 *     parameters"*);
 *   · ardından cihaz self-documentation'ı (`*` ya da `"` ile başlayan satırlar).
 * Böylece kaç parametre satırı olduğu ÖNEMSİZLEŞİR; kanal bit hızı gibi
 * konumla okunan alanlar yoksa `undefined` kalır, uydurulmaz.
 *
 * ── İLERİ UYUMLULUK REHBERİN KENDİ KURALIDIR ────────────────────────────────
 * 4.0'ın sürüm notu: *"New records introduced in 4.x or later XIF files must be
 * followed by a blank line and 4.x interpreters should discard unknown records
 * and their contents up to the next blank line."* Tanınmayan kayıt bu yüzden
 * TEK uyarı üretip bir sonraki boş satıra kadar atlanır — satır satır uyarı
 * basmak yeni bir kayıt tipi eklenen dosyada ekranı gürültüye boğardı.
 *
 * TUZAK — SATIR SONU: XIF dosyaları Windows araçlarıyla üretilir; ölçüldü,
 * `WNC-FT-B-303.XIF` CRLF taşıyor. `\r` kırpılmazsa `*` karşılaştırması ve
 * self-documentation metinleri görünmez karakterle bozulur.
 */

import type {
  XifConfigFile,
  XifDatabase,
  XifDevice,
  XifFileInfo,
  XifMessageTag,
  XifNetworkVariable,
  XifNvDirection,
  XifParseIssue,
  XifParseResult,
  XifServiceType,
  XifTypeElement,
} from './xifTypes';

const ISSUE_TEXT_LIMIT = 120;
const DECIMAL_RADIX = 10;
const HEX_RADIX = 16;

/**
 * Sorun sebepleri ÇEVİRİ ANAHTARIDIR (CLAUDE.md): görünen hiçbir metin koda
 * gömülmez. Satır numarası ve ham metin ayrı alanlarda taşınır.
 */
const ISSUE_EMPTY_INPUT = 'definition.xif.issue.emptyInput';
const ISSUE_NO_HEADER = 'definition.xif.issue.noHeader';
const ISSUE_MALFORMED_FILE_LINE = 'definition.xif.issue.malformedFileLine';
const ISSUE_UNKNOWN_RECORD = 'definition.xif.issue.unknownRecord';
const ISSUE_TRUNCATED_RECORD = 'definition.xif.issue.truncatedRecord';
const ISSUE_NV_COUNT_MISMATCH = 'definition.xif.issue.nvCountMismatch';
const ISSUE_TAG_COUNT_MISMATCH = 'definition.xif.issue.tagCountMismatch';
const ISSUE_NV_VALUE_OVERFLOW = 'definition.xif.issue.nvValueOverflow';
const ISSUE_DUPLICATE_NV_INDEX = 'definition.xif.issue.duplicateNvIndex';

/** Rehberin satır 1 söz dizimi: `File: fileName generated by toolName, XIF Version major.minor`. */
const FILE_LINE_PATTERN =
  /^File:\s*(\S+)\s+generated\s+by\s+(.+?)\s*,\s*XIF\s+Version\s+(\d+)\.(\d+)\s*$/i;
/** Satır 3'ün zorunlu zaman damgası: `... Run on day month date hh:mm:ss year`. */
const TIMESTAMP_PATTERN = /\bRun\s+on\s+(.+?)\s*$/i;
/** Satır 5: sekiz iki-haneli hex, iki nokta üst üste ayraçlı, BOŞLUKSUZ. */
const PROGRAM_ID_PATTERN = /^[0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){7}$/;
/** Sayısal başlık parametresi satırı: yalnız tam sayılar ve `*` (rehber: `*` = varsayılan). */
const NUMERIC_FIELD_PATTERN = /^(?:[-+]?\d+|\*)$/;

/** Bilinen kayıt anahtar sözcükleri — başlık taraması bunlardan birine çarparsa durur. */
const RECORD_KEYWORDS = new Set(['VAR', 'TAG', 'FILE', 'NVVAL']);

function clip(text: string): string {
  const trimmed = text.trim();
  return trimmed.length <= ISSUE_TEXT_LIMIT ? trimmed : `${trimmed.slice(0, ISSUE_TEXT_LIMIT)}…`;
}

function fieldsOf(line: string): readonly string[] {
  const trimmed = line.trim();
  return trimmed === '' ? [] : trimmed.split(/\s+/);
}

/**
 * Tam sayı alanı. Rehberin kuralı: *"Integer fields contain zero when they are
 * not applicable, and asterisks when they are default values."* — yani `*`
 * SIFIR DEĞİLDİR, "bu dosyada belirtilmemiş"tir ve `undefined` döner.
 */
function parseIntegerField(token: string | undefined): number | undefined {
  if (token === undefined || token === '*') return undefined;
  const value = Number.parseInt(token, DECIMAL_RADIX);
  return Number.isFinite(value) ? value : undefined;
}

function parseIntegerOrZero(token: string | undefined): number {
  return parseIntegerField(token) ?? 0;
}

/** Boolean alanlar rehberde 0/1'dir; `*` ve eksik alan `false` sayılır. */
function parseFlag(token: string | undefined): boolean {
  return token === '1';
}

function parseDirection(token: string | undefined): XifNvDirection {
  // Rehber satır 2 alan 4: 0 giriş, 1 çıkış. LonScan da aynı yönde okuyor.
  return token === '1' ? 'output' : 'input';
}

function parseServiceType(token: string | undefined): XifServiceType | undefined {
  switch (token) {
    case '0':
      return 'acknowledged';
    case '1':
      return 'repeated';
    case '2':
      return 'unacknowledged';
    default:
      return undefined;
  }
}

/**
 * Rehberin ikili (binary) içerik kuralı — `FILE` gövdesi ve `NVVAL` satırları
 * için AYNI kural geçerli:
 *
 * *"Each value may optionally start with a '0x' or '\x' prefix. Values may
 * optionally be separated with commas or spaces. If separators are not used,
 * every pair of values represents one hex byte."*
 *
 * AYRAÇ VARSA her belirteç TEK bayttır (tek haneli olabilir: `7` → 0x07);
 * AYRAÇ YOKSA haneler İKİŞER eşlenir. Bu ayrım rehberin kendi beş örneğinin
 * (`7,89,ab,cd` ile `0789abcd` aynı dört baytı verir) hepsini karşılar; tek
 * bir kuralla okumak ilk örnekte `78 9a bc d?` üretirdi.
 */
function parseHexBytes(text: string): readonly number[] {
  // `0x` ve `\x` önekleri değer taşımaz, önce düşer.
  const withoutPrefixes = text.replace(/0x|\\x/gi, ' ');
  const tokens = withoutPrefixes.split(/[\s,]+/).filter((token) => token !== '');
  if (tokens.length === 0) return [];

  const bytes: number[] = [];
  if (tokens.length > 1) {
    for (const token of tokens) {
      const cleaned = token.replace(/[^0-9A-Fa-f]/g, '');
      if (cleaned === '') continue;
      const value = Number.parseInt(cleaned, HEX_RADIX);
      if (Number.isFinite(value)) bytes.push(value & 0xff);
    }
    return bytes;
  }

  const digits = (tokens[0] ?? '').replace(/[^0-9A-Fa-f]/g, '');
  for (let index = 0; index + 1 < digits.length; index += 2) {
    const value = Number.parseInt(digits.slice(index, index + 2), HEX_RADIX);
    if (Number.isFinite(value)) bytes.push(value);
  }
  // Tek kalan hane rehberde temsil edilemez; sessizce düşürmek yerine son
  // baytın yarısını uydurmamak için atlanır.
  return bytes;
}

/**
 * Karakter biçimli `FILE` içerik satırı: ilk `"` atılır, İKİNCİ `"` dizeyi
 * bitirir ve sonrası okunmaz (rehberin kendi cümlesi). `\xHH` kaçışları
 * çözülür — burada çözülür çünkü hedef BAYT, self-documentation'ın aksine
 * (orada metin VERİDİR ve ham kalır).
 */
function parseQuotedContentLine(line: string): readonly number[] {
  const afterQuote = line.slice(line.indexOf('"') + 1);
  const terminator = afterQuote.indexOf('"');
  const body = terminator === -1 ? afterQuote : afterQuote.slice(0, terminator);

  const bytes: number[] = [];
  for (let index = 0; index < body.length; index += 1) {
    const escape = /^\\x([0-9A-Fa-f]{2})/.exec(body.slice(index));
    if (escape !== null) {
      bytes.push(Number.parseInt(escape[1] ?? '0', HEX_RADIX));
      index += 3;
      continue;
    }
    bytes.push(body.charCodeAt(index) & 0xff);
  }
  return bytes;
}

/** Yorum satırı: rehber *"If the first non-blank character on a line is '#', the entire line is ignored."* */
function isComment(line: string): boolean {
  return line.trim().startsWith('#');
}

interface Cursor {
  readonly lines: readonly string[];
  index: number;
}

function peek(cursor: Cursor): string | undefined {
  return cursor.lines[cursor.index];
}

/** 1'den başlayan dosya satır numarası — bütün `XifParseIssue.line` değerleri buradan. */
function lineNumber(cursor: Cursor): number {
  return cursor.index + 1;
}

/**
 * Self-documentation bloğu: tek `*` (yok) ya da `"` ile başlayan satırlar.
 * Satırlar ARADA HİÇBİR KARAKTER OLMADAN birleştirilir (rehber). `\xHH`
 * kaçışları ÇÖZÜLMEZ: bu metin ekranda gösterilen VERİdir, bayt değil —
 * çözmek görünmez kontrol karakterlerini arayüze taşırdı.
 */
function readSelfDocumentation(cursor: Cursor): string {
  const first = peek(cursor);
  if (first !== undefined && first.trim() === '*') {
    cursor.index += 1;
    return '';
  }

  const parts: string[] = [];
  for (;;) {
    const line = peek(cursor);
    if (line === undefined || !line.trimStart().startsWith('"')) break;
    parts.push(line.trimStart().slice(1));
    cursor.index += 1;
  }
  return parts.join('');
}

function readVarRecord(
  cursor: Cursor,
  issues: XifParseIssue[],
): XifNetworkVariable | undefined {
  const recordLine = lineNumber(cursor);
  const header = fieldsOf(peek(cursor) ?? '');
  cursor.index += 1;

  const name = header[1];
  if (name === undefined) {
    issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(header.join(' ')) });
    return undefined;
  }

  const attributesLine = peek(cursor);
  if (attributesLine === undefined) {
    issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(name) });
    return undefined;
  }
  const attributes = fieldsOf(attributesLine);
  cursor.index += 1;

  const selfDocumentation = readSelfDocumentation(cursor);

  const typeLine = peek(cursor);
  if (typeLine === undefined) {
    issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(name) });
    return undefined;
  }
  // Rehber: `snvtIndex * elementCount` — ORTA belirteç ayrılmış bir alandır ve
  // gerçek dosyalarda daima `*`tır; konumla okunur, değeri yorumlanmaz.
  const typeFields = fieldsOf(typeLine);
  cursor.index += 1;
  const snvtIndex = parseIntegerOrZero(typeFields[0]);
  const elementCount = parseIntegerField(typeFields[2]) ?? 1;

  const elements: XifTypeElement[] = [];
  for (let read = 0; read < elementCount; read += 1) {
    const elementLine = peek(cursor);
    if (elementLine === undefined) {
      issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(name) });
      break;
    }
    const element = fieldsOf(elementLine);
    cursor.index += 1;
    elements.push({
      type: parseIntegerOrZero(element[0]),
      bitOffset: parseIntegerOrZero(element[1]),
      size: parseIntegerOrZero(element[2]),
      signed: parseFlag(element[3]),
      arraySize: parseIntegerOrZero(element[4]),
    });
  }

  return {
    name,
    index: parseIntegerOrZero(header[2]),
    avgRateEncoded: parseIntegerOrZero(header[3]),
    maxRateEncoded: parseIntegerOrZero(header[4]),
    // `arraySize` 2.0'da eklendi; 1.0 dosyalarında alan HİÇ YOKTUR.
    arraySize: parseIntegerOrZero(header[5]),
    takeOfflineToUpdate: parseFlag(attributes[0]),
    direction: parseDirection(attributes[3]),
    serviceType: parseServiceType(attributes[4]),
    serviceTypeConfigurable: parseFlag(attributes[5]),
    authenticated: parseFlag(attributes[6]),
    authenticationConfigurable: parseFlag(attributes[7]),
    priority: parseFlag(attributes[8]),
    priorityConfigurable: parseFlag(attributes[9]),
    polled: parseFlag(attributes[10]),
    synchronized: parseFlag(attributes[11]),
    configClass: parseFlag(attributes[12]),
    selfDocumentation,
    snvtIndex,
    elementCount,
    elements,
    defaultValue: undefined,
    line: recordLine,
  };
}

function readTagRecord(cursor: Cursor, issues: XifParseIssue[]): XifMessageTag | undefined {
  const recordLine = lineNumber(cursor);
  const header = fieldsOf(peek(cursor) ?? '');
  cursor.index += 1;

  const name = header[1];
  if (name === undefined) {
    issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(header.join(' ')) });
    return undefined;
  }

  const attributesLine = peek(cursor);
  if (attributesLine === undefined) {
    issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(name) });
    return undefined;
  }
  const attributes = fieldsOf(attributesLine);
  cursor.index += 1;

  return {
    name,
    index: parseIntegerOrZero(header[2]),
    avgRateEncoded: parseIntegerOrZero(header[3]),
    maxRateEncoded: parseIntegerOrZero(header[4]),
    // Rehber: ikinci satırın söz dizimi `0 bindFlag 63 1 0 1 0 1 0 1 0 0 0`.
    bindable: parseFlag(attributes[1]),
    line: recordLine,
  };
}

function readFileRecord(cursor: Cursor, issues: XifParseIssue[]): XifConfigFile | undefined {
  const recordLine = lineNumber(cursor);
  const header = fieldsOf(peek(cursor) ?? '');
  cursor.index += 1;

  const name = header[1];
  if (name === undefined) {
    issues.push({ line: recordLine, messageKey: ISSUE_TRUNCATED_RECORD, text: clip(header.join(' ')) });
    return undefined;
  }

  const contents: number[] = [];
  for (;;) {
    const line = peek(cursor);
    // Rehber: içerik bir BOŞ SATIRLA biter.
    if (line === undefined || line.trim() === '') break;
    cursor.index += 1;
    if (isComment(line)) continue;
    contents.push(
      ...(line.trimStart().startsWith('"') ? parseQuotedContentLine(line) : parseHexBytes(line)),
    );
  }

  return {
    name,
    index: parseIntegerOrZero(header[2]),
    type: parseIntegerOrZero(header[3]),
    declaredLength: parseIntegerField(header[4]),
    contents,
    line: recordLine,
  };
}

/**
 * `NVVAL` bölümü: her satır BİR konfigürasyon NV'sinin varsayılan değeri ve
 * SIRA bildirim sırasıdır (rehber: *"The order of the definitions must match
 * the order of declaration of the configuration network variables"*). Eşleme
 * bu yüzden ada değil SIRAYA göre yapılır — XIF'te CPNV adları eşsiz olmak
 * zorunda değildir (4.401 sürüm notu programatik ad tekrarını ayrıca ele alır).
 */
function readNvValueSection(cursor: Cursor): readonly (readonly number[])[] {
  cursor.index += 1;
  const values: (readonly number[])[] = [];
  for (;;) {
    const line = peek(cursor);
    if (line === undefined || line.trim() === '') break;
    cursor.index += 1;
    if (isComment(line)) continue;
    values.push(parseHexBytes(line));
  }
  return values;
}

/**
 * XIF metnini çözer. Fırlatmaz; bozuk satırlar `issues` olarak döner.
 *
 * `success: false` yalnız BAŞLIK kurulamadığında verilir (`xifTypes.ts`teki
 * gerekçe: sıfır NV taşıyan XIF GEÇERLİDİR, `izot/shortstack`ın 20 microserver
 * dosyasında ölçüldü).
 */
export function parseXif(text: string): XifParseResult {
  const issues: XifParseIssue[] = [];

  if (text.trim() === '') {
    return { success: false, issues: [{ line: 0, messageKey: ISSUE_EMPTY_INPUT }] };
  }

  // CRLF tuzağı: `\r` kırpılmazsa `*` karşılaştırması ve metinler bozulur.
  const lines = text.split('\n').map((line) => line.replace(/\r$/, ''));
  const cursor: Cursor = { lines, index: 0 };

  let fileName = '';
  let generatedBy = '';
  let formatVersion = '';
  let formatMajor: number | undefined;
  let formatMinor: number | undefined;
  let timestamp = '';
  let programId = '';
  let programIdFound = false;

  // ── Başlık: satır 1 ile satır 5 (program ID) arası ────────────────────────
  let sawFileLine = false;
  while (cursor.index < lines.length) {
    const line = peek(cursor) ?? '';
    const trimmed = line.trim();
    if (trimmed === '' || isComment(line)) {
      cursor.index += 1;
      continue;
    }
    if (RECORD_KEYWORDS.has(fieldsOf(line)[0] ?? '')) break;

    if (PROGRAM_ID_PATTERN.test(trimmed)) {
      programId = trimmed;
      programIdFound = true;
      cursor.index += 1;
      break;
    }

    if (!sawFileLine) {
      sawFileLine = true;
      const match = FILE_LINE_PATTERN.exec(trimmed);
      if (match === null) {
        issues.push({ line: lineNumber(cursor), messageKey: ISSUE_MALFORMED_FILE_LINE, text: clip(trimmed) });
      } else {
        fileName = match[1] ?? '';
        generatedBy = match[2] ?? '';
        formatMajor = parseIntegerField(match[3]);
        formatMinor = parseIntegerField(match[4]);
        formatVersion = `${match[3] ?? ''}.${match[4] ?? ''}`;
      }
    }

    if (timestamp === '') {
      const stamp = TIMESTAMP_PATTERN.exec(trimmed);
      if (stamp !== null) timestamp = stamp[1] ?? '';
    }
    cursor.index += 1;
  }

  if (!programIdFound) {
    // Başlık XIF'in TEK zorunlu bölümüdür; program ID bulunamadıysa gösterilecek
    // bir cihaz yoktur.
    return { success: false, issues: [...issues, { line: 0, messageKey: ISSUE_NO_HEADER }] };
  }

  // ── Sayısal parametre satırları, `*` görülene dek ─────────────────────────
  const parameterLines: (readonly string[])[] = [];
  while (cursor.index < lines.length) {
    const line = peek(cursor) ?? '';
    const trimmed = line.trim();
    if (trimmed === '*') {
      cursor.index += 1;
      break;
    }
    if (trimmed === '') {
      cursor.index += 1;
      continue;
    }
    const tokens = fieldsOf(line);
    if (!tokens.every((token) => NUMERIC_FIELD_PATTERN.test(token))) break;
    parameterLines.push(tokens);
    cursor.index += 1;
  }

  const deviceSelfDocumentation = readSelfDocumentation(cursor);

  // Rehberin satır 6 alanları; konumlar sabittir ve BÜTÜN sürümlerde geçerlidir.
  const line6 = parameterLines[0] ?? [];
  // Satır 9 alan 1 = kanal bit hızı. Satır 8/9/10 YALNIZ 3.0+'da vardır, o
  // yüzden dizi konumu yoksa `undefined` kalır — sıfır uydurulmaz.
  const line9 = parameterLines[3];

  const device: XifDevice = {
    programId,
    selfDocumentation: deviceSelfDocumentation,
    domainCount: parseIntegerField(line6[0]),
    addressTableEntries: parseIntegerField(line6[1]),
    declaredStaticNvCount: parseIntegerField(line6[3]),
    declaredMessageTagCount: parseIntegerField(line6[4]),
    channelBitRate: line9 === undefined ? undefined : parseIntegerField(line9[0]),
  };

  // ── Kayıt bölümleri ───────────────────────────────────────────────────────
  const networkVariables: XifNetworkVariable[] = [];
  const messageTags: XifMessageTag[] = [];
  const configFiles: XifConfigFile[] = [];
  let nvValues: readonly (readonly number[])[] = [];
  let reportedUnknownRecord = false;

  while (cursor.index < lines.length) {
    const line = peek(cursor) ?? '';
    if (line.trim() === '' || isComment(line)) {
      cursor.index += 1;
      continue;
    }

    switch (fieldsOf(line)[0]) {
      case 'VAR': {
        const record = readVarRecord(cursor, issues);
        if (record !== undefined) networkVariables.push(record);
        continue;
      }
      case 'TAG': {
        const record = readTagRecord(cursor, issues);
        if (record !== undefined) messageTags.push(record);
        continue;
      }
      case 'FILE': {
        const record = readFileRecord(cursor, issues);
        if (record !== undefined) configFiles.push(record);
        continue;
      }
      case 'NVVAL': {
        nvValues = readNvValueSection(cursor);
        continue;
      }
      default: {
        // 4.0'ın ileri uyumluluk kuralı: bilinmeyen kayıt bir sonraki BOŞ
        // satıra kadar atlanır ve yalnız BİR kez uyarı üretir.
        if (!reportedUnknownRecord) {
          reportedUnknownRecord = true;
          issues.push({ line: lineNumber(cursor), messageKey: ISSUE_UNKNOWN_RECORD, text: clip(line) });
        }
        while (cursor.index < lines.length && (peek(cursor) ?? '').trim() !== '') {
          cursor.index += 1;
        }
        continue;
      }
    }
  }

  // ── Bildirilen sayılarla bulunanları karşılaştır ──────────────────────────
  if (
    device.declaredStaticNvCount !== undefined &&
    device.declaredStaticNvCount !== networkVariables.length
  ) {
    issues.push({
      line: 0,
      messageKey: ISSUE_NV_COUNT_MISMATCH,
      text: `${String(device.declaredStaticNvCount)} / ${String(networkVariables.length)}`,
    });
  }
  if (
    device.declaredMessageTagCount !== undefined &&
    device.declaredMessageTagCount !== messageTags.length
  ) {
    issues.push({
      line: 0,
      messageKey: ISSUE_TAG_COUNT_MISMATCH,
      text: `${String(device.declaredMessageTagCount)} / ${String(messageTags.length)}`,
    });
  }

  const seenIndexes = new Set<number>();
  for (const variable of networkVariables) {
    if (seenIndexes.has(variable.index)) {
      issues.push({
        line: variable.line,
        messageKey: ISSUE_DUPLICATE_NV_INDEX,
        text: clip(variable.name),
      });
    }
    seenIndexes.add(variable.index);
  }

  // `NVVAL` değerleri konfigürasyon sınıfı NV'lere BİLDİRİM SIRASIYLA bağlanır.
  const configIndexes = networkVariables
    .map((variable, position) => (variable.configClass ? position : -1))
    .filter((position) => position !== -1);
  if (nvValues.length > configIndexes.length) {
    issues.push({
      line: 0,
      messageKey: ISSUE_NV_VALUE_OVERFLOW,
      text: `${String(nvValues.length)} / ${String(configIndexes.length)}`,
    });
  }
  const withValues = networkVariables.map((variable) => variable);
  for (let position = 0; position < Math.min(nvValues.length, configIndexes.length); position += 1) {
    const target = configIndexes[position];
    const value = nvValues[position];
    const variable = target === undefined ? undefined : withValues[target];
    if (target === undefined || variable === undefined || value === undefined) continue;
    withValues[target] = { ...variable, defaultValue: value };
  }

  const fileInfo: XifFileInfo = {
    fileName,
    generatedBy,
    formatVersion,
    formatMajor,
    formatMinor,
    timestamp,
  };

  const database: XifDatabase = {
    fileInfo,
    device,
    networkVariables: withValues,
    messageTags,
    configFiles,
  };
  return { success: true, database, issues };
}

/** NV indeksine göre network variable arar. */
export function findXifNetworkVariable(
  database: XifDatabase,
  index: number,
): XifNetworkVariable | undefined {
  return database.networkVariables.find((variable) => variable.index === index);
}

/**
 * Configuration property olarak GERÇEKLENEN network variable'lar (CPNV).
 *
 * XIF'te ayrı bir CP kaydı YOKTUR (`xifTypes.ts` dosya başı); bir CP ya böyle
 * bir NV'dir ya da bir `FILE` kaydının içindedir.
 */
export function selectXifConfigProperties(
  database: XifDatabase,
): readonly XifNetworkVariable[] {
  return database.networkVariables.filter((variable) => variable.configClass);
}
